version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-cache-v1-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-cache-v1-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Lint Source
          command: yarn lint

      - run:
          name: Run Tests
          command: yarn test

      - run:
          name: Build
          command: yarn build:lib

      - store_artifacts:
          path: dist

      - persist_to_workspace:
          root: ~/repo
          paths:
            - scripts
            - dist

  deploy:
    docker:
      - image: circleci/node:8.11.3-browsers

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          name: Configure NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

      - run:
          name: Publish Packages
          command: |
            cd /tmp/workspace

            for d in dist/*/; do
              packageName=`basename $d`

              echo "Deploying $packageName"

              npm publish "$d" --access public
            done

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
